from setuptools import setup, find_packages

setup(
    name="quant_trade_a_share",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "pandas>=1.3.0",
        "numpy>=1.20.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "tushare>=1.2.0",
        "baostock>=0.8.0",
        "yfinance>=0.1.0",
        "plotly>=4.0.0",
        "dash>=2.0.0",
        "scipy>=1.7.0",
        "statsmodels>=0.12.0",
        "requests>=2.25.0",
        "qlib>=0.9.0",
    ],
    author="Quant Trader",
    author_email="quant@example.com",
    description="A quantitative trading tool for A-Share market",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/your-repo/quant-trade-a-share",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
)