#!/usr/bin/env python3
"""
Terminal-based Stock Signals Visualizer for A-Share Market
Displays all signals generated by various strategies in the terminal
"""

import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import sqlite3
import warnings
warnings.filterwarnings('ignore')

# Add the project root to the path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from quant_trade_a_share.signals.signal_notifier import SignalNotifier
from quant_trade_a_share.strategies.strategy_tools import StrategyManager
from quant_trade_a_share.utils.eastmoney_data_fetcher import EastMoneyDataFetcher
from quant_trade_a_share.screeners.stock_screener import StockScreener


def create_terminal_chart(data, title="Stock Price Chart", width=80, height=20):
    """
    Create a simple ASCII chart in the terminal
    """
    if data.empty or 'close' not in data.columns:
        return "No data available for chart"

    # Get close prices
    prices = data['close'].values

    # Normalize prices to fit the terminal chart
    min_price = min(prices)
    max_price = max(prices)
    price_range = max_price - min_price

    if price_range == 0:
        return "Price data is constant"

    # Scale prices to terminal chart height
    scaled_prices = [(p - min_price) / price_range * (height - 1) for p in prices]

    # Create the chart
    chart = []

    # Add title
    chart.append(f"  {title}".ljust(width))

    # Add Y-axis labels and chart rows
    for y in range(height - 1, -1, -1):
        row = f"{max_price - (y / (height - 1)) * price_range:6.2f} |"
        for x, scaled_price in enumerate(scaled_prices):
            if int(scaled_price) == y:
                row += "*"
            elif int(scaled_price) == y + 1 or int(scaled_price) == y - 1:
                row += "."
            else:
                row += " "
        chart.append(row)

    # Add X-axis
    chart.append("       +" + "-" * (len(prices) - 1))

    # Add date labels at intervals
    date_labels = ""
    for i in range(0, len(data.index), max(1, len(data.index) // (width // 10))):
        date_labels += f"{data.index[i].strftime('%m-%d'):>10}"
    chart.append(f"        {date_labels}")

    return "\n".join(chart)


def display_signals_table(signals, limit=20):
    """
    Display signals in a nicely formatted table in the terminal
    """
    if not signals:
        print("No signals found in database.")
        return

    print("\n" + "="*100)
    print(f"{'#' :<4} {'Time':<20} {'Symbol':<12} {'Type':<8} {'Strategy':<15} {'Price':<10} {'Reason':<25}")
    print("="*100)

    for i, signal in enumerate(signals[:limit], 1):
        signal_type = f"📈BUY" if signal['signal_type'] == 'BUY' else f"📉SELL" if signal['signal_type'] == 'SELL' else f"⏸️HOLD"
        price = f"¥{signal['price']:.2f}" if signal['price'] else "N/A"
        reason = signal['reason'][:23] + ".." if len(signal['reason']) > 25 else signal['reason']

        print(f"{i:<4} {signal['timestamp'][:19]:<20} {signal['symbol']:<12} {signal_type:<8} {signal['strategy']:<15} {price:<10} {reason:<25}")

    print("="*100)
    print(f"Total signals shown: {len(signals[:limit])}/{len(signals)}")


def visualize_signals_for_stock(symbol, days=60):
    """
    Generate and visualize signals for a specific stock
    """
    print(f"\n🔍 Analyzing signals for {symbol}")
    print("-" * 60)

    # Initialize components
    fetcher = EastMoneyDataFetcher()
    strategy_manager = StrategyManager()
    notifier = SignalNotifier()

    # Try to get stock data from EastMoney first
    print(f"📊 Fetching {days} days of data for {symbol}...")
    data = fetcher.fetch_stock_data(symbol, days=days)

    # If EastMoney fails, try to get from screener
    if data is None or data.empty:
        print(f"⚠️ EastMoney failed, trying alternative source...")
        screener = StockScreener()
        data = screener.fetch_stock_data(symbol, period=str(days))

    if data is None or data.empty:
        print(f"❌ Could not fetch data for {symbol}")
        # Just display existing signals from database for this stock
        print(f"📊 Showing existing signals for {symbol} from database:")
        recent_signals = notifier.get_signals_by_stock(symbol, limit=10)
        if recent_signals:
            display_signals_table(recent_signals, limit=10)
        else:
            print("  No recent signals found for this stock in database")
        return

    print(f"✅ Retrieved {len(data)} days of data")

    # Display ASCII chart
    chart_title = f"{symbol} - Price Movement (Last {days} Days)"
    chart = create_terminal_chart(data, title=chart_title, width=80, height=15)
    print(chart)

    # Generate signals using multiple strategies
    print(f"\n🧠 Generating signals using various strategies...")

    strategy_results = {}

    # Get all available strategies
    strategy_names = strategy_manager.get_strategy_names()

    for strategy_name in strategy_names[:5]:  # Limit to first 5 strategies to avoid too much output
        try:
            strategy = strategy_manager.get_strategy(strategy_name)
            if strategy:
                print(f"  Running {strategy_name} strategy...")
                signals = strategy.generate_signals(data)

                # Count signals
                buy_signals = len(signals[signals == 1])
                sell_signals = len(signals[signals == -1])
                hold_signals = len(signals[signals == 0])

                strategy_results[strategy_name] = {
                    'buy': buy_signals,
                    'sell': sell_signals,
                    'hold': hold_signals,
                    'signals': signals
                }

                print(f"    BUY: {buy_signals}, SELL: {sell_signals}, HOLD: {hold_signals}")

                # Add signals to notifier
                for idx, signal_val in signals.items():
                    if signal_val == 1:  # Buy signal
                        notifier.add_signal(
                            symbol=symbol,
                            name=symbol.upper(),  # Would get real name in practice
                            signal_type="BUY",
                            strategy=strategy_name,
                            price=data.loc[idx, 'close'] if 'close' in data.columns else None,
                            reason=f"{strategy_name} strategy generated buy signal",
                            priority=2
                        )
                    elif signal_val == -1:  # Sell signal
                        notifier.add_signal(
                            symbol=symbol,
                            name=symbol.upper(),
                            signal_type="SELL",
                            strategy=strategy_name,
                            price=data.loc[idx, 'close'] if 'close' in data.columns else None,
                            reason=f"{strategy_name} strategy generated sell signal",
                            priority=2
                        )

        except Exception as e:
            print(f"  ❌ Error running {strategy_name}: {e}")

    # Display recent signals from database
    print(f"\n🔔 Recent signals for {symbol}:")
    recent_signals = notifier.get_signals_by_stock(symbol, limit=10)
    if recent_signals:
        display_signals_table(recent_signals, limit=10)
    else:
        print("  No recent signals found for this stock")

    # Summary of all strategies
    print(f"\n📋 Strategy Summary for {symbol}:")
    print("-" * 80)
    print(f"{'Strategy':<20} {'BUY':<8} {'SELL':<8} {'HOLD':<8} {'Latest Signal':<15}")
    print("-" * 80)

    for strat_name, results in strategy_results.items():
        latest_signal = "N/A"
        if len(results['signals']) > 0:
            last_sig = results['signals'].iloc[-1]
            latest_signal = "BUY" if last_sig == 1 else "SELL" if last_sig == -1 else "HOLD"

        print(f"{strat_name:<20} {results['buy']:<8} {results['sell']:<8} {results['hold']:<8} {latest_signal:<15}")

    print("-" * 80)


def display_all_signals(db_path="signals.db", limit=50):
    """
    Display all signals in the database
    """
    print("\n📡 Displaying ALL signals in database")
    print("=" * 120)

    notifier = SignalNotifier(db_path)
    all_signals = notifier.get_recent_signals(limit)

    if all_signals:
        display_signals_table(all_signals, limit=limit)

        # Summary statistics
        df = pd.DataFrame(all_signals)

        print(f"\n📊 Signal Statistics:")
        print(f"   Total signals: {len(all_signals)}")
        print(f"   BUY signals: {len(df[df['signal_type'] == 'BUY'])}")
        print(f"   SELL signals: {len(df[df['signal_type'] == 'SELL'])}")
        print(f"   Unique stocks: {df['symbol'].nunique()}")
        print(f"   Strategies used: {df['strategy'].nunique()} - {', '.join(df['strategy'].unique())}")

        # Top stocks by signal count
        top_stocks = df['symbol'].value_counts().head(10)
        print(f"\n🥇 Top 10 stocks by signal count:")
        for stock, count in top_stocks.items():
            print(f"   {stock}: {count} signals")

    else:
        print("No signals found in database.")


def main():
    """
    Main function to run the terminal signal visualization
    """
    print("📈 A-Share Stock Signals Terminal Visualizer")
    print("=" * 60)
    print("This tool analyzes stock signals and displays them in the terminal")
    print("using various trading strategies and visual representations.")

    # Run default analysis on top stocks
    print("\n🔍 Running quick analysis on top stocks...")
    # Use some sample stocks
    top_stocks = ['sh600519', 'sz000858']  # Using fewer stocks for quicker demo

    for stock in top_stocks:
        visualize_signals_for_stock(stock, days=30)

    # Then show all signals in database
    print("\n" + "="*60)
    display_all_signals(limit=20)

    print("\n👋 Analysis complete!")


if __name__ == "__main__":
    main()